
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 14 2024 16:02:47 IST (Nov 14 2024 10:32:47 UTC)

// Verification Directory fv/HOERAA 

module fulladder(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__2398(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_10(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5107(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_9(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__6260(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_8(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__4319(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_7(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__8428(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module fulladder_6(X, Y, Ci, S, Co);
  input X, Y, Ci;
  output S, Co;
  wire X, Y, Ci;
  wire S, Co;
  ADDFX1 g66__5526(.A (X), .B (Y), .CI (Ci), .CO (Co), .S (S));
endmodule

module RCA_N6(X, Y, Ci, S, Co);
  input [5:0] X, Y;
  input Ci;
  output [5:0] S;
  output Co;
  wire [5:0] X, Y;
  wire Ci;
  wire [5:0] S;
  wire Co;
  wire [4:0] w;
  fulladder \adder_stage[0].genblk1.FA (X[0], Y[0], Ci, S[0], w[0]);
  fulladder_10 \adder_stage[1].genblk1.FA (X[1], Y[1], w[0], S[1],
       w[1]);
  fulladder_9 \adder_stage[2].genblk1.FA (X[2], Y[2], w[1], S[2], w[2]);
  fulladder_8 \adder_stage[3].genblk1.FA (X[3], Y[3], w[2], S[3], w[3]);
  fulladder_7 \adder_stage[4].genblk1.FA (X[4], Y[4], w[3], S[4], w[4]);
  fulladder_6 \adder_stage[5].genblk1.FA (X[5], Y[5], w[4], S[5], Co);
endmodule

module HOERAA(X, Y, S, Co);
  input [15:0] X, Y;
  output [15:0] S;
  output Co;
  wire [15:0] X, Y;
  wire [15:0] S;
  wire Co;
  wire Ci, n_0, n_1;
  assign S[0] = 1'b1;
  assign S[1] = 1'b1;
  assign S[2] = 1'b1;
  assign S[3] = 1'b1;
  assign S[4] = 1'b1;
  assign S[5] = 1'b1;
  assign S[6] = 1'b1;
  assign S[7] = 1'b1;
  RCA_N6 accurate_subadder(X[15:10], Y[15:10], Ci, S[15:10], Co);
  OAI21XL g80__6783(.A0 (n_0), .A1 (Ci), .B0 (n_1), .Y (S[9]));
  NAND3XL g81__3680(.A (X[8]), .B (Y[8]), .C (Ci), .Y (n_1));
  OR2XL g82__1617(.A (Y[8]), .B (X[8]), .Y (S[8]));
  NOR2XL g83__2802(.A (Y[9]), .B (X[9]), .Y (n_0));
  AND2X1 g84__1705(.A (X[9]), .B (Y[9]), .Y (Ci));
endmodule

